### ISSUE TITLE
[2.3 Preview] Increased Discord Disconnects / Console Hangs

### ISSUE THREAD

**Issue by drkshrk** [Eco-DiscordLink/EcoDiscordPlugin#54]
Increased disconnects and console hangs with preview version compared to 2.2.1 - Investigating

**Comment by MonzUn** [comment]
The disconnects are most likely because of Discord being bad.

The hangs may or may not be related to the disconnects.

**Comment by drkshrk** [comment]
-Need to verify but I believe leaving the config box open on the GUI for discordlink  for a long period of time will cause discordlink to break.  I Will update if I reproduce this at a later point - just didn't want to forget.

**Comment by MonzUn** [comment]
I may have solved this. I will wait and see if I get any more hangs after I've deployed the fix.

**Comment by drkshrk** [comment]
Your fixes have definitely improved this.  I haven't had a console hang-up since.  I still get the discord disconnects on occasion but alot more random. (Only happened once that i have seen since your update)

**Comment by MonzUn** [comment]
Yeah I feel that too, but running for 2 days still have a deadlock. I did some minor changes and added more logging and I'm running that on my server now.

**Comment by MonzUn** [comment]
Closing this for now as it has been stable on EcoWorld for a week now.
