### ISSUE TITLE
Issue with /dl-link as elevetade guild member intent does not work

### ISSUE THREAD

**Issue by Alteraner** [Eco-DiscordLink/EcoDiscordPlugin#62]
Hello,
 i tried to link my account using /dl-link in game but I get below error message:

![image](https://user-images.githubusercontent.com/47274045/136955596-36f748e5-2cc5-4f58-94f9-9a6fa0cf73a4.png)

I checked the bot configuration but the required permission has been given:

![image](https://user-images.githubusercontent.com/47274045/136955660-aba21fe1-05e2-466d-aa9d-7167d4be9d17.png)

Still get the error. As there is no documentation around that feature I need to raise this issue here to figure out whats going wrong or if there is a bug.
Sorry.

**Comment by MonzUn** [comment]
Thanks for the report.
This might be caused by Discord updating things that is not yet updated by DL.

I see that the name is different name for example.

The only troubleshooting tips I can give is to restart the plugin/server and to double check that you're using the token for the bot application that you have given the permissions too.

I'll keep this open in case more people report the same thing.

**Comment by Alteraner** [comment]
Thank you @MonzUn for your quick feedback. All the other DL features in Discord running well. So we can chat, and get all the server status and updates all the time. Only this feature is not working. 

what do you mean with "different name"?

Are there any further permissions needed on the discord server to get it up and running?

**Comment by MonzUn** [comment]
I saw in your screenshot that's it's called "Server Members Intent" now instead "Guild Members Intent".

It means the same thing. I just wanted to highlight that even if DL doesn't change, Discord might and that may break things.

No, that's the only one you should need.

**Comment by Provant15** [comment]
I am experiencing the same issue. Any fixes on this?

**Comment by MonzUn** [comment]
No. I can't reproduce the issue and none of the users I have frequent contact with are experiencing any issue like this.

**Comment by Provant15** [comment]
> No. I can't reproduce the issue and none of the users I have frequent contact with are experiencing any issue like this.


I'd be happy to link up with you and let you take a look so you could perhaps dive into it? Otherwise pointing me in the right direction as to where I might be able to look to fix it would be awesome.

**Comment by MonzUn** [comment]
My suspicion is that the problem is on Discord's end. My checks for this are super simple so there isn't really anything to look at. I just ask Discord if the bot has the intent or not.

If it's an API change, then it should be fixed with the next update that changes the DSharp version (if they still update, Discord has been fucking over bot devs hard so it's not certain).

**Comment by Provant15** [comment]
Right I see, I reinstalled the plugin/mod again to see if I missed a step along the way, unfortunately still have the same results.

Hopefully sorts itself out soon.

**Comment by MonzUn** [comment]
It's not set up during install.
It's done when creating the bot user, so reinstalling doesn't do anything.

**Comment by Provant15** [comment]
> It's not set up during install. It's done when creating the bot user, so reinstalling doesn't do anything.

Yes that's what I meant. I reinstalled the plugin/mod and rebuilt the bot. Same issues.

Actually is now throwing up a new issue as a result of doing that.

![image](https://user-images.githubusercontent.com/11922416/144155465-4d719016-20df-43c7-b797-08046ac6dc35.png)

This was trying to use "?Trades UserName" which was working prior to reconfiguring.

**Comment by kotoroshinoto** [comment]
The guild member intent setting doesn't exist under that name anymore. 
![image](https://user-images.githubusercontent.com/1337560/147708628-51807e69-a7c4-4f77-95d2-f526383d9c99.png)
It describes that it grants permissions to all the guild member settings though, so it OUGHT to work. Despite granting this, the mod thinks it doesn't have this permission, so they might have changed its name slightly.

**Comment by MonzUn** [comment]
Yeah, I know it's been changed and I'll update the docs to reflect that in the 3.0 update.

Account linking is bugged anyway in the current version so it's not a big deal.

Compile bleeding edge if you want to make use of the feature.

**Comment by kotoroshinoto** [comment]
I was using the latest tagged commit. didn't want to hazard a bleeding edge build, as I know from experience how much that can break something ;p

**Comment by MonzUn** [comment]
The latest tagged commit mostly has small changes for compatibility with Eco. The DSharp version you're using is from before april 2021.

I always run bleeding edge on EcoWorld, so it should be relatively safe to run.

**Comment by VelvetToroyashi** [comment]
> I was using the latest tagged commit. didn't want to hazard a bleeding edge build, as I know from experience how much that can break something ;p

We try to not introduce breaking changes without notification. 

Hopefully some testing will be underway and a stable release of 4.2.0 will be pushed soon. 👍🏽

**Comment by MonzUn** [comment]
Ah, I think they meant the latest tagged commit of my game server plugin.
Which means that they are using a version that has an outdated DSharp version, so it's probably fixed as soon as I make my next release with a more up to date DSharp version, feel free to close this and I'll reopen if using the latest version doesn't solve the issue :)

**Comment by Asharas** [comment]
Hi!
Is there anything one can do to fix this when lacking access to the game's sources?
My server's citizens would like to use this feature.

Thanks in advance :)

**Comment by MonzUn** [comment]
Compile and run 3.0 or wait until 3.0 is released.

**Comment by Asharas** [comment]
That I gathered from the previous messages, I expected a more detailed answer for someone unfamiliar with C# or Eco modding.
If I'm able to do it without the game sources I'd like to contribute a CI pipeline for nightly builds so others in my case can have the latest commit compiled.

Could you add those intructions in the README for an upcoming release please?

**Comment by MonzUn** [comment]
I prefer if people who run unsupported builds are code savvy enough to be able to figure out issues themselves as that creates better information for me and less support problems. So I can't say I'm motivated to provide something like that. I break the builds all the time as well as I'm literally the only tester. If more people were running bleeding edge, I'd feel more preassure to fix things I break quickly as it affects more people and that sort of stress I'm afraid will take out the fun of modding and it will become more like my actual professional work.

IMO, the problem here is that the public release got neglected because of all the refactoring and rewrites I wanted to do all at once. Didn't want to break th config over and over, so I pushed things to get all of the things into one build instead. In the future, the release cadence will be better and this should make it so there is less incentive to run bleeding edge.

**Comment by Asharas** [comment]
I understand the concerns. 
I happen to be code savyy but as a system architect it's just not my specialty to jump into a new language. I can find my way but I could use a couple indications like figuring out required dependencies because, as far as I understood from the repo's doc, game's sources are needed (hence my first question being "when lacking access to the game's sources").
If they aren't required I can just set up a headless temporary environment and compile, if it breaks I'll know I'm on an unstable version (there's a reason why the systems I manage use stable package repos).

Also, if you could define the level of information you expect in an issue about bleeding edge, I could use it as a reference for submitting or not a problem. I've dug up php and python to change/fix small things (yes, one could argue about python).
A couple clues about the compile process could save me time as I'm currently working on an Ansible role to deploy an Eco server (and actually currently integrating your mod into it).

Last argument in the pool, I've never had the occasion to work on Github Actions and since I like your mod and would like to contribute up to my skills, I figured it'd be a good purpose to learn GH CI (my clients and I all use Gitlab).

If you'd rather not have bleeding edge publicly available, could we work this out by DM or email? 

I hope those arguments will convince you, if not I'll wait for 3.0  ¯\\_(ツ)_/¯

Anyway, my users and I love the mod, thanks for maintaining it, if you're open to suggestions I'll submit those in issues.

**Comment by MonzUn** [comment]
The server/game source is not needed. The top comment there is actually because before SLG started supplying them, people were grabbing them in a manner of different ways which I couldn't put into a guide. Nowadays, you can just go grab them from play.eco.

I'll make sure to update that doc when I do the docs overhaul for 3.0

Issues on bleeding edge would be the same as for non-bleeding edge.
Description, STR etc, but I'd also want a commit hash from where it's built I guess.

The compile process should be outlined in the setup docs.
Add dependencies and compile basically. The rest is set up in the msbuild file.

I know very little about github actions, but yeah. We could discuss it on Discord. Currently I'm swamped with work though so I might take a bit to get back to you.

Thanks, I'm definitely open to suggestions! They are encouraged ^^

**Comment by KevinGelking** [comment]
We're also hitting this issue and I grabbed the plugin via ' eco.mod.io ' where it's at v2.2.3 EM v3.1.1 ; I'm not sure where I'd be able to snatch and build the 3.0 version that supposedly fixes the linking issue?

It might be develop; or it might be the 'eco 9.5' branch which seems to be the latest; but as there's no clear way to tell which version is the one including that fix, I would much appreciate a pointer in the right direction and I'm sure others would, too.

Wouldn't it perhaps be possible to link a release on Github (like the others) but as [Experimental] so it's easier to ensure that people who do grab the WIP version at least have the same state?

**Comment by MonzUn** [comment]
`Develop` always targets the current official Eco release. Any other branch will either have the target in the name or have it be unkown.
I have already stated that I will not support any other builds than the officially released ones and that the issue described in this thread is of very little importance in the current official release.

To be clear: I will NOT release ANY experimental builds.
If you want experimental builds, you will have to build them yourself.

Locking the thread as all relevant information has already been stated and the issue is already resolved in a future release.

**Comment by MonzUn** [comment]
This problem should be resolved in 3.0.0
